/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'JongKwang' at '8/9/17 4:34 AM' with Gradle 2.14.1
 *
 * @author JongKwang, @date 8/9/17 4:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
